# -*- coding: utf-8 -*-
"""movie-recommender-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156iVLkJBnsbl2zBweHX1qLAO2arfolSF
"""

import pandas as pd
import numpy as np

movies = pd.read_csv("/content/drive/MyDrive/datasets/TMDB 5000 Movie Dataset/tmdb_5000_movies.csv")
credits = pd.read_csv("/content/drive/MyDrive/datasets/TMDB 5000 Movie Dataset/tmdb_5000_credits.csv")

movies.head(1)

movies.iloc[0].production_companies

credits.head(1)

credits.head(1)['crew'].values

movies = movies.merge(credits, on='title')

movies.columns

# columns to keep
# genres
# movie_id
# keywords
# title
# overview
# cast
# crew

movies = movies[['genres','movie_id','keywords','title','overview','cast','crew']]

movies.head(1)

"""# Preprocessing

## 1. missing data handeling
"""

movies.isnull().sum()

movies.dropna(inplace=True)

"""# 2. dublicate data"""

movies.duplicated().sum()

movies.iloc[0].genres

import ast

def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

movies['genres'] = movies['genres'].apply(convert)

movies.iloc[0].genres

movies['keywords'] = movies['keywords'].apply(convert)

movies['keywords']

movies['cast']

def convert3(obj):
  L = []
  counter=0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

movies['cast'] = movies['cast'].apply(convert3)

movies['crew'][0]

def fetch_diractor(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

movies['crew'] = movies['crew'].apply(fetch_diractor)
movies['crew']

movies.head(1)

movies.overview = movies.overview.apply(lambda x: x.split())

movies.head(1)

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['overview'] = movies['overview'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies.head(1)

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

movies.tags[0]

new_df = movies[['movie_id','title', 'tags']]
new_df

new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

new_df

new_df['tags'][0]

new_df.tags = new_df.tags.apply(lambda x: x.lower())
new_df['tags'][0]

import nltk

from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

new_df['tags'] = new_df['tags'].apply(stem)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors[0]

cv.get_feature_names_out()

vectors.shape

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity[1]

def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)
  return

recommend('Avatar')

new_df[new_df['title'] == 'Batman Begins']

new_df[new_df['title'] == 'Batman Begins'].index[0]

new_df[new_df['title'] == 'Avatar'].index[0]

new_df.head(1)

import pickle

pickle.dump(new_df, open('movies.pkl', 'wb'))

pickle.dump(similarity, open('similarity.pkl', 'wb'))

